env:
  browser: true
  es6: true
  node: true
extends:
  # - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  # - "prettier/@typescript-eslint"
  # - "plugin:prettier/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-namespace": "off"
  "@typescript-eslint/no-unused-vars":
    - 2
    - argsIgnorePattern: "^_"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  comma-dangle:
    - "error"
    - "always-multiline"
  import/prefer-default-export: off
settings:
  import/resolver:
    node:
    webpack:
      config:
        - "webpack.config.dev.ts"
        - "webpack.config.prod.ts"
  react:
    version: detect
